defaultPortal: ECP1
portals:
  - name: ECP1
    portalId: 21007727
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMOjorDRLxIJAA0AAAAA4A0DGO-aggoguJz_DCju6QwyFFcuifsvcGGlCzVqUuq1ORMTBMC5OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTnruS4-kJj2ImzDJXf0AHGXxKxYUoDbmExUgBaAA
        expiresAt: '2021-11-12T21:23:20.138Z'
    personalAccessKey: >-
      CiQ0NzdmN2RlOS1jMDMyLTRkNWYtOTVmNi0xZTIxY2EwYTYxYzQQ75qCChi4nP8MKhkABeaRgjbawefThK98yPaZF_tByunFBuYzSgNuYTE
