defaultPortal: ECP1
portals:
  - name: ECP1
    portalId: 21007727
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJvg96LSLxIJAA0AAAAA4A0DGO-aggoguJz_DCju6QwyFB2ARaLe8_WZN6NSLyoW2_NvbgbNOigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhRE4quO3qKQ9wQh_E0yaGMC4wKcMkoDbmExUgBaAA
        expiresAt: '2021-11-15T16:11:15.874Z'
    personalAccessKey: >-
      CiQ0NzdmN2RlOS1jMDMyLTRkNWYtOTVmNi0xZTIxY2EwYTYxYzQQ75qCChi4nP8MKhkABeaRgjbawefThK98yPaZF_tByunFBuYzSgNuYTE
