defaultPortal: ECP1
portals:
  - name: ECP1
    portalId: 21007727
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKf9pK_RLxIJAA0AAAAA4A0DGO-aggoguJz_DCju6QwyFMPZbFbA2lRd1u66or2JwpLbIqG_OigAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgQhTM0tFoeqxPI8wNhoM4_z6nHVVGJUoDbmExUgBaAA
        expiresAt: '2021-11-12T20:49:07.245Z'
    personalAccessKey: >-
      CiQ0NzdmN2RlOS1jMDMyLTRkNWYtOTVmNi0xZTIxY2EwYTYxYzQQ75qCChi4nP8MKhkABeaRgjbawefThK98yPaZF_tByunFBuYzSgNuYTE
